import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  Timer, ChevronRight, AlertCircle, CheckCircle2, XCircle, 
  Lock, Zap, ChevronLeft, ArrowRight, Sparkles, Network,
  RefreshCw, Lightbulb, History, BookOpen, Brain, Copy, CheckSquare
} from 'lucide-react'
import questionsData from '../data/questions.json'
import { supabase } from '../lib/supabase'
import { generateQuestions, generateExplanation, generateAINotes } from '../lib/ai'

// ── Paywall Modal ─────────────────────────────────────────────
const PaywallModal = ({ isOpen, onClose }) => {
  const [passcode, setPasscode] = useState('')
  
  const handleUnlock = () => {
    if (passcode === 'EDTECH2026' || passcode === 'admin123') {
       localStorage.setItem('premium_unlocked', 'true')
       window.location.reload()
    } else {
       alert('Incorrect passcode!')
    }
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-6 backdrop-blur-md bg-black/60">
          <motion.div 
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="glass-card max-w-lg w-full p-10 relative overflow-hidden text-center space-y-8 border-brand-primary/30"
          >
            <div className="w-20 h-20 bg-gradient-to-tr from-brand-primary to-brand-secondary rounded-3xl mx-auto flex items-center justify-center shadow-xl shadow-brand-primary/30">
              <Lock className="text-white fill-white" size={32} />
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl font-black font-sans tracking-tight">Unlock <span className="gradient-text">Concept Intelligence</span></h2>
              <p className="text-text-muted leading-relaxed font-medium px-4">
                Enter your secret passcode to unlock step-by-step reasoning, prerequisite maps, and unlimited AI tutoring.
              </p>
            </div>
            <div className="flex flex-col gap-4 items-center">
              <input 
                type="password" 
                placeholder="Enter Secret Passcode" 
                value={passcode}
                onChange={e => setPasscode(e.target.value)}
                className="px-6 py-4 rounded-xl bg-[var(--color-surface-card)] border border-[var(--color-border)] text-center text-lg font-bold w-full focus:outline-none focus:border-brand-primary transition-colors text-text-primary"
              />
              <button 
                onClick={handleUnlock}
                className="w-full primary-btn py-4 text-lg font-black shadow-lg shadow-brand-primary/20 hover:scale-[1.02] transition-all"
              >
                Unlock Premium Now
              </button>
              <button onClick={onClose} className="text-sm font-bold text-text-muted hover:text-text-primary transition-colors py-2">
                Continue with limited version
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}

// ── AI Notes Panel ─────────────────────────────────────────────
function AINotesPanel({ exam, subject, mistakes }) {
  const [query, setQuery] = useState('')
  const [loading, setLoading] = useState(false)
  const [notes, setNotes] = useState(null)
  const [copied, setCopied] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false)

  useEffect(() => {
    // Auto-generate from mistakes if any exist
    if (mistakes && mistakes.length > 0 && !autoGenerated) {
      handleGenerateFromMistakes()
    }
  }, [mistakes])

  const handleGenerateFromMistakes = async () => {
    if (!mistakes || mistakes.length === 0) return
    setLoading(true)
    setAutoGenerated(true)
    try {
      const result = await generateAINotes(exam, subject, mistakes)
      if (result) setNotes(result)
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  const handleGenerateCustom = async (e) => {
    e?.preventDefault()
    if (!query.trim()) return
    setLoading(true)
    setNotes(null)
    try {
      const { generateExplanation: ge } = await import('../lib/ai')
      const result = await ge(
        `Generate comprehensive conceptual notes for: ${query} in context of ${exam} ${subject}.`,
        'concept request', 'detailed study notes', exam
      )
      if (result) {
        setNotes({
          title: query,
          brief: result.brief,
          sections: [
            { heading: 'Core Concepts', content: result.deep, points: result.prerequisites || [] }
          ],
          oneLiner: result.tip || 'Focus on fundamentals first.'
        })
      }
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = () => {
    if (!notes) return
    const text = `${notes.title}\n\n${notes.brief}\n\n${notes.sections?.map(s => `${s.heading}\n${s.content}\n${s.points?.join('\n')}`).join('\n\n')}\n\nTip: ${notes.oneLiner}`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-br from-amber-500/10 to-transparent p-6 rounded-2xl border border-amber-500/20">
        <div className="flex items-center gap-2 text-amber-500 mb-2">
          <Sparkles size={18} className="fill-amber-500" />
          <h3 className="font-black text-sm uppercase tracking-widest">AI Smart Notes</h3>
        </div>
        <p className="text-text-muted text-xs leading-relaxed">
          {mistakes?.length > 0 
            ? `Auto-generating notes from your ${mistakes.length} mistake(s) in this session.`
            : 'Search any topic to get AI-powered study notes.'
          }
        </p>
      </div>

      {/* Custom search */}
      <form onSubmit={handleGenerateCustom} className="flex gap-2">
        <input
          type="text"
          value={query}
          onChange={e => setQuery(e.target.value)}
          placeholder={`Search ${subject} topic...`}
          className="flex-1 bg-[var(--color-input-bg)] border border-[var(--color-border)] rounded-xl px-4 py-3 text-sm font-medium outline-none focus:border-amber-500/50 placeholder:text-text-muted/50 transition-all"
        />
        <button
          type="submit"
          disabled={loading || !query.trim()}
          className="bg-amber-500 hover:bg-amber-600 text-white px-4 rounded-xl font-black text-xs transition-all disabled:opacity-50 flex items-center gap-1"
        >
          {loading ? <div className="animate-spin rounded-full h-4 w-4 border-t-2 border-white" /> : <><Brain size={14}/> GO</>}
        </button>
      </form>

      {/* Notes Output */}
      <AnimatePresence mode="wait">
        {loading ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="flex flex-col items-center justify-center py-12 space-y-4">
            <div className="relative">
              <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-amber-500" />
              <Sparkles size={20} className="absolute inset-0 m-auto text-amber-500 animate-pulse" />
            </div>
            <p className="text-xs font-black text-text-muted uppercase tracking-widest">Architecting notes...</p>
          </motion.div>
        ) : notes ? (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
            <div className="flex items-start justify-between">
              <div>
                <h4 className="font-black text-base">{notes.title}</h4>
                <p className="text-xs text-text-muted mt-1 leading-relaxed">{notes.brief}</p>
              </div>
              <button onClick={handleCopy} className="p-2 hover:bg-[var(--color-surface-card-hover)] rounded-lg border border-[var(--color-border)] text-text-muted hover:text-text-primary transition-all shrink-0">
                {copied ? <CheckSquare size={16} className="text-green-500" /> : <Copy size={16} />}
              </button>
            </div>

            <div className="space-y-4 max-h-[400px] overflow-y-auto pr-1">
              {notes.sections?.map((section, idx) => (
                <div key={idx} className="glass-card p-4 space-y-2">
                  <p className="text-[10px] font-black text-amber-500 uppercase tracking-widest">{section.heading}</p>
                  <p className="text-xs leading-relaxed text-text-muted">{section.content}</p>
                  {section.points?.length > 0 && (
                    <ul className="space-y-1.5 mt-2">
                      {section.points.map((point, pi) => (
                        <li key={pi} className="text-xs font-medium flex items-start gap-2">
                          <CheckCircle2 size={12} className="text-amber-500 mt-0.5 shrink-0" />
                          {point}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
              {notes.oneLiner && (
                <div className="p-4 rounded-2xl bg-amber-500/5 border border-amber-500/20">
                  <p className="text-[10px] font-black text-amber-500 uppercase tracking-widest mb-1">💡 One-Liner Tip</p>
                  <p className="text-sm font-bold italic">"{notes.oneLiner}"</p>
                </div>
              )}
            </div>

            {mistakes?.length > 0 && (
              <button
                onClick={handleGenerateFromMistakes}
                disabled={loading}
                className="w-full py-3 rounded-xl border border-amber-500/30 text-amber-500 text-xs font-black uppercase tracking-widest hover:bg-amber-500/10 transition-all flex items-center justify-center gap-2"
              >
                <RefreshCw size={12} /> Regenerate from Mistakes
              </button>
            )}
          </motion.div>
        ) : (
          <div className="py-12 flex flex-col items-center justify-center opacity-40 text-center space-y-3">
            <BookOpen size={40} className="text-text-muted" />
            <p className="text-xs font-bold uppercase tracking-widest text-text-muted">
              {mistakes?.length > 0 ? 'Generating notes from mistakes...' : 'Search a topic above'}
            </p>
          </div>
        )}
      </AnimatePresence>
    </div>
  )
}

// ── Main Practice Component ────────────────────────────────────
export default function Practice() {
  const { exam, subject } = useParams()
  const navigate = useNavigate()

  const [questions, setQuestions] = useState([])
  const [currentIndex, setCurrentIndex] = useState(0)
  const [selectedOption, setSelectedOption] = useState(null)
  const [isSubmitted, setIsSubmitted] = useState(false)
  const [score, setScore] = useState(0)
  const [timer, setTimer] = useState(0)
  const [isPremium, setIsPremium] = useState(false)
  const [showPaywall, setShowPaywall] = useState(false)
  const [mistakesCount, setMistakesCount] = useState(0)
  const [aiInsight, setAiInsight] = useState(null)
  const [currentExam, setCurrentExam] = useState(exam || 'JEE')
  const [isGeneratingQuestions, setIsGeneratingQuestions] = useState(false)
  const [isLoadingInsight, setIsLoadingInsight] = useState(false)
  const [usedAI, setUsedAI] = useState(false)
  const [sessionMistakes, setSessionMistakes] = useState([])
  const [userId, setUserId] = useState(null)
  const [activeTab, setActiveTab] = useState('test') // 'test' | 'notes'

  useEffect(() => {
    const init = async () => {
      const { data: { session } } = await supabase.auth.getSession()
      let activeExam = exam || 'JEE'
      if (session?.user) {
        setUserId(session.user.id)
        if (!exam) activeExam = session.user.user_metadata?.target_exam || 'JEE'
        if (localStorage.getItem('premium_unlocked') === 'true' || session.user.user_metadata?.is_premium || session.user.user_metadata?.subscription === 'premium') {
          setIsPremium(true)
        }
      }
      setCurrentExam(activeExam)
      await loadQuestions(activeExam, subject)
    }
    init()
    const interval = setInterval(() => setTimer(t => t + 1), 1000)
    return () => clearInterval(interval)
  }, [subject, exam])

  const loadQuestions = async (examType, subjectName) => {
    setIsGeneratingQuestions(true)
    let seenQuestions = JSON.parse(localStorage.getItem('seen_questions_' + subjectName) || '[]')
    let finalSelection = []

    try {
      const timeoutPromise = new Promise((_, reject) => setTimeout(() => reject(new Error('AI timeout')), 8000))
      // Ask AI for 15 questions to ensure we have enough buffer for 10 non-repeaters
      const aiQuestionsPromise = generateQuestions(examType, subjectName, 15, 'medium')
      const aiQuestions = await Promise.race([aiQuestionsPromise, timeoutPromise])
      
      if (aiQuestions && Array.isArray(aiQuestions) && aiQuestions.length >= 5) {
        setUsedAI(true)
        const unseenAi = aiQuestions.filter(q => !seenQuestions.includes(q.question))
        finalSelection = unseenAi.length >= 10 ? unseenAi.slice(0, 10) : aiQuestions.slice(0, 10)
      }
    } catch (err) { 
      console.warn('AI failed, using robust fallback.') 
      setUsedAI(false)
    }

    if (finalSelection.length < 10) {
      // SILENT FALLBACK: Fill exactly 10 questions from local database
      let filtered = questionsData.filter(q => q.exam === examType && q.subject === subjectName)
      if (filtered.length === 0) filtered = questionsData // Ultimate fallback
      
      let unseen = filtered.filter(q => !seenQuestions.includes(q.question))
      
      // If we don't have enough unseen questions, it means they've done multiple mock tests.
      // Fill the rest with seen questions, but prioritize least-recently seen.
      // Or just shuffle everything if unseen is totally empty.
      if (unseen.length === 0) {
         localStorage.setItem('seen_questions_' + subjectName, '[]')
         seenQuestions = []
         unseen = filtered
      }

      let shuffledUnseen = [...unseen].sort(() => Math.random() - 0.5)
      
      if (shuffledUnseen.length >= 10) {
         finalSelection = shuffledUnseen.slice(0, 10)
      } else {
         // Not enough unseen. Take all unseen, and pad with shuffled seen questions.
         let seenPool = filtered.filter(q => seenQuestions.includes(q.question)).sort(() => Math.random() - 0.5)
         finalSelection = [...shuffledUnseen, ...seenPool].slice(0, 10)
      }
    }

    // Ensure we always have exactly 10 if padding was weird (rare edge case in tiny JSONs)
    while (finalSelection.length < 10 && finalSelection.length > 0) {
      finalSelection.push({...finalSelection[Math.floor(Math.random() * finalSelection.length)], question: finalSelection[0].question + " (Variant " + Math.random().toString(36).substring(7) + ")"})
    }

    // Shuffle the OPTIONS for each question so they never look the same across attempts
    const shuffledWithOptions = finalSelection.slice(0, 10).map(q => ({
      ...q,
      options: q.options ? [...q.options].sort(() => Math.random() - 0.5) : q.options
    }))

    setQuestions(shuffledWithOptions)
    setIsGeneratingQuestions(false)
  }

  const handleRegenerate = async () => {
    setCurrentIndex(0); setSelectedOption(null); setIsSubmitted(false)
    setScore(0); setTimer(0); setMistakesCount(0); setAiInsight(null); setSessionMistakes([])
    await loadQuestions(currentExam, subject)
  }

  const formatTime = (s) => `${Math.floor(s / 60)}:${(s % 60).toString().padStart(2, '0')}`

  const triggerAIInsight = async (correct, q) => {
    if (!correct) {
      setMistakesCount(prev => prev + 1)
      setIsLoadingInsight(true)
      const insight = await generateExplanation(q.question, selectedOption, q.answer, currentExam)
      const insightData = insight || {
        classification: 'Concept Gap',
        brief: 'Review the relationship between the variables.',
        deep: q.explanation + ' Focus on the derivation.',
        prerequisites: q.prerequisites || ['Fundamental Concepts'],
        tip: 'Always start by writing the formula.'
      }
      setAiInsight(insightData)
      setSessionMistakes(prev => [...prev, {
        question: q.question, yourAnswer: selectedOption,
        correctAnswer: q.answer, explanation: insightData.brief,
        deepExplanation: insightData.deep, topic: q.topic
      }])
      setIsLoadingInsight(false)
      if (!isPremium && mistakesCount === 0) setTimeout(() => setShowPaywall(true), 2000)
    }
  }

  const handleSubmit = () => {
    if (!selectedOption) return
    setIsSubmitted(true)
    const currentQ = questions[currentIndex]
    const isCorrect = selectedOption === currentQ.answer
    if (isCorrect) setScore(s => s + 4); else setScore(s => s - 1)
    triggerAIInsight(isCorrect, currentQ)
  }

  // ── Save to Supabase ──────────────────────────────────────────
  const saveAttemptToSupabase = async (finalScore, finalMistakes, time) => {
    if (!userId) return
    try {
      const { data: attempt, error } = await supabase.from('attempts').insert({
        user_id: userId,
        exam: currentExam,
        subject: subject,
        score: finalScore,
        total_questions: questions.length,
        time_spent: time,
        mistakes_count: finalMistakes.length,
        mistakes_data: JSON.stringify(finalMistakes),
        accuracy: Math.round(((questions.length - finalMistakes.length) / questions.length) * 100)
      }).select().single()

      if (error) console.warn('Supabase save (may need schema update):', error.message)
      else console.log('✅ Attempt saved to Supabase:', attempt?.id)
    } catch (err) {
      console.warn('Supabase insert failed:', err.message)
    }

    // Always save to localStorage as backup
    const sessionData = {
      date: new Date().toISOString(), exam: currentExam, subject,
      score: finalScore, timeSpent: time, mistakesCount: finalMistakes.length,
      accuracy: Math.round(((questions.length - finalMistakes.length) / questions.length) * 100),
      mistakes: finalMistakes
    }
    const history = JSON.parse(localStorage.getItem('practiceHistory') || '[]')
    history.unshift(sessionData) // Add to beginning
    localStorage.setItem('practiceHistory', JSON.stringify(history.slice(0, 20)))

    // Save seen questions for non-repeating logic
    const seen = JSON.parse(localStorage.getItem('seen_questions_' + subject) || '[]')
    const newSeen = [...new Set([...seen, ...questions.map(q => q.question)])]
    localStorage.setItem('seen_questions_' + subject, JSON.stringify(newSeen))
  }

  const handleNext = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(currentIndex + 1); setSelectedOption(null)
      setIsSubmitted(false); setAiInsight(null)
    } else {
      // Navigate FIRST immediately so user never gets stuck
      const resultState = {
        exam: currentExam, subject, score, timeSpent: timer,
        mistakesCount, totalQuestions: questions.length, mistakes: sessionMistakes
      }
      // Save to localStorage synchronously as backup so it's always available
      const sessionData = {
        date: new Date().toISOString(), exam: currentExam, subject,
        score, timeSpent: timer, mistakesCount,
        accuracy: Math.round(((questions.length - sessionMistakes.length) / questions.length) * 100),
        mistakes: sessionMistakes
      }
      try {
        const history = JSON.parse(localStorage.getItem('practiceHistory') || '[]')
        history.unshift(sessionData)
        localStorage.setItem('practiceHistory', JSON.stringify(history.slice(0, 20)))
        const seen = JSON.parse(localStorage.getItem('seen_questions_' + subject) || '[]')
        const newSeen = [...new Set([...seen, ...questions.map(q => q.question)])]
        localStorage.setItem('seen_questions_' + subject, JSON.stringify(newSeen))
      } catch(e) {}
      
      // Navigate immediately — don't wait for Supabase
      navigate('/result', { state: resultState })
      
      // Fire-and-forget Supabase background save (don't await, don't block)
      saveAttemptToSupabase(score, sessionMistakes, timer)
    }
  }

  // ── Loading States ────────────────────────────────────────────
  if (isGeneratingQuestions) return (
    <div className="h-full flex flex-col items-center justify-center p-20 glass-card">
      <div className="relative mb-8">
        <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-brand-primary" />
        <Sparkles size={24} className="absolute inset-0 m-auto text-brand-primary animate-pulse" />
      </div>
      <h2 className="text-2xl font-bold mb-2">Generating Questions</h2>
      <p className="text-text-muted text-sm font-medium">Preparing your {currentExam} {subject} session...</p>
    </div>
  )

  if (questions.length === 0) return (
    <div className="h-full flex flex-col items-center justify-center p-20 glass-card">
      <AlertCircle size={48} className="text-brand-primary mb-6 animate-pulse" />
      <h2 className="text-2xl font-bold mb-4">No questions found</h2>
      <p className="text-text-muted text-sm mb-6">Try a different subject or exam.</p>
      <div className="flex gap-4">
        <button onClick={() => navigate(-1)} className="secondary-btn">Go Back</button>
        <button onClick={handleRegenerate} className="primary-btn flex items-center gap-2">
          <RefreshCw size={16} /> Generate with AI
        </button>
      </div>
    </div>
  )

  const currentQ = questions[currentIndex]
  const progress = ((currentIndex + 1) / questions.length) * 100

  return (
    <div className="max-w-5xl mx-auto space-y-8 page-transition pb-20">
      <PaywallModal isOpen={showPaywall} onClose={() => setShowPaywall(false)} />

      {/* HUD */}
      <div className="flex items-center justify-between glass-card p-5 shadow-2xl">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate(-1)} className="p-3 hover:bg-[var(--color-surface-card-hover)] rounded-2xl transition-all border border-transparent hover:border-[var(--color-border)] group">
            <ChevronLeft size={20} className="group-hover:-translate-x-1 transition-transform" />
          </button>
          <div>
            <h2 className="text-base font-bold flex items-center gap-2 flex-wrap">
              <span className="text-brand-primary font-black uppercase tracking-widest text-[10px] bg-brand-primary/10 px-2 py-0.5 rounded-full">{currentExam}</span>
              {subject}
              {usedAI && (
                <span className="text-[10px] font-black bg-gradient-to-r from-brand-primary to-brand-secondary text-white px-2 py-0.5 rounded-full flex items-center gap-1">
                  <Sparkles size={10} /> AI
                </span>
              )}
            </h2>
            <div className="flex items-center gap-4 text-xs font-bold text-text-muted mt-0.5">
              <span className="flex items-center gap-1"><Timer size={12} className="text-brand-secondary" /> {formatTime(timer)}</span>
              <span className="flex items-center gap-1"><Sparkles size={12} className="text-brand-accent" /> Score: <span className="text-text-primary">{score}</span></span>
              <span className="flex items-center gap-1"><AlertCircle size={12} className="text-red-400" /> Mistakes: {mistakesCount}</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button onClick={handleRegenerate} className="p-2 hover:bg-[var(--color-surface-card-hover)] rounded-xl transition-all border border-transparent hover:border-[var(--color-border)]" title="New questions">
            <RefreshCw size={16} className="text-text-muted hover:text-brand-primary hover:rotate-180 transition-all duration-500" />
          </button>
          <div className="min-w-40 space-y-1">
            <div className="flex justify-between text-[10px] font-black tracking-widest text-text-muted uppercase">
              <span>Q {currentIndex + 1}/{questions.length}</span>
              <span className="text-brand-primary">{Math.round(progress)}%</span>
            </div>
            <div className="h-2 bg-[var(--color-input-bg)] rounded-full overflow-hidden border border-[var(--color-border)]">
              <motion.div initial={{ width: 0 }} animate={{ width: `${progress}%` }}
                className="h-full bg-gradient-to-r from-brand-primary to-brand-secondary" />
            </div>
          </div>
        </div>
      </div>

      {/* Tab Switcher */}
      <div className="flex gap-1 p-1 bg-[var(--color-surface-card)] border border-[var(--color-border)] rounded-2xl w-fit">
        {[
          { id: 'test', label: '📝 Mock Test' },
          { id: 'notes', label: '✨ AI Notes' }
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-5 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${
              activeTab === tab.id
                ? 'bg-brand-primary text-white shadow-lg shadow-brand-primary/20'
                : 'text-text-muted hover:text-text-primary'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <AnimatePresence mode="wait">
        {activeTab === 'test' ? (
          <motion.div key="test" initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 10 }}
            className="grid grid-cols-1 lg:grid-cols-4 gap-8">

            {/* Question Area */}
            <div className="lg:col-span-3 space-y-6">
              <motion.div key={currentIndex} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}
                className="glass-card p-10 relative overflow-hidden group shadow-2xl min-h-52">
                <div className="absolute top-0 right-0 p-8 opacity-[0.03] pointer-events-none -z-10 group-hover:opacity-[0.05] transition-opacity">
                  <Zap size={120} />
                </div>
                {currentQ.topic && (
                  <p className="text-[10px] font-black text-brand-primary uppercase tracking-widest mb-4 flex items-center gap-2">
                    <Lightbulb size={12} /> {currentQ.topic}
                    {currentQ.difficulty && (
                      <span className={`ml-2 px-2 py-0.5 rounded-full text-[9px] ${
                        currentQ.difficulty === 'easy' ? 'bg-green-500/10 text-green-500' :
                        currentQ.difficulty === 'hard' ? 'bg-red-500/10 text-red-500' :
                        'bg-amber-500/10 text-amber-500'}`}>
                        {currentQ.difficulty.toUpperCase()}
                      </span>
                    )}
                  </p>
                )}
                <p className="text-xl font-bold font-sans leading-relaxed">{currentQ.question}</p>
              </motion.div>

              <div className="grid grid-cols-1 gap-3">
                {currentQ.options.map((opt, i) => {
                  const isCorrect = opt === currentQ.answer
                  const isSelected = opt === selectedOption
                  let stateStyles = 'border-[var(--color-border)] hover:bg-[var(--color-surface-card-hover)]'
                  if (isSubmitted) {
                    if (isCorrect) stateStyles = 'border-green-500 bg-green-500/10 text-green-400 font-bold'
                    else if (isSelected) stateStyles = 'border-red-500 bg-red-500/10 text-red-500 font-bold'
                    else stateStyles = 'border-[var(--color-border)] opacity-40'
                  } else if (isSelected) {
                    stateStyles = 'border-brand-primary bg-brand-primary/10 shadow-lg shadow-brand-primary/10'
                  }
                  return (
                    <motion.button key={i}
                      whileHover={!isSubmitted ? { scale: 1.01, x: 6 } : {}}
                      whileTap={!isSubmitted ? { scale: 0.99 } : {}}
                      onClick={() => { if (!isSubmitted) setSelectedOption(opt) }}
                      className={`relative p-5 px-8 rounded-2xl border text-left transition-all duration-200 flex items-center justify-between font-medium ${stateStyles}`}>
                      <div className="flex items-center gap-5">
                        <span className={`w-8 h-8 rounded-full border flex items-center justify-center font-bold text-xs shrink-0 ${
                          isSelected ? 'bg-brand-primary text-white border-brand-primary' : 'bg-[var(--color-surface-card)] border-[var(--color-border)] text-text-muted'}`}>
                          {String.fromCharCode(65 + i)}
                        </span>
                        {opt}
                      </div>
                      {isSubmitted && isCorrect && <CheckCircle2 className="text-green-400 shrink-0" size={22} />}
                      {isSubmitted && isSelected && !isCorrect && <XCircle className="text-red-500 shrink-0" size={22} />}
                    </motion.button>
                  )
                })}
              </div>

              {!isSubmitted ? (
                <button onClick={handleSubmit} disabled={!selectedOption}
                  className="w-full primary-btn py-5 rounded-3xl text-lg font-black tracking-widest disabled:opacity-30 shadow-2xl shadow-brand-primary/20 hover:scale-[1.01] active:scale-[0.98] transition-all flex items-center justify-center gap-4 group h-18">
                  CONFIRM ANSWER <ArrowRight size={22} className="group-hover:translate-x-2 transition-transform" />
                </button>
              ) : (
                <button onClick={handleNext}
                  className="w-full py-5 rounded-3xl bg-[var(--color-surface-card)] border border-[var(--color-border)] hover:bg-[var(--color-surface-card-hover)] text-lg font-black tracking-widest h-18 shadow-2xl hover:scale-[1.01] active:scale-[0.98] transition-all flex items-center justify-center gap-4 group uppercase">
                  {currentIndex < questions.length - 1 ? 'Next Question' : 'Finish Session'} <ChevronRight size={22} className="group-hover:translate-x-2 transition-transform" />
                </button>
              )}
            </div>

            {/* AI Insight Sidebar */}
            <div className="lg:col-span-1 space-y-5">
              <AnimatePresence>
                {isSubmitted && (isLoadingInsight || aiInsight) && (
                  <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-5">
                    {isLoadingInsight ? (
                      <div className="glass-card p-8 flex flex-col items-center justify-center space-y-4 border-brand-accent/20">
                        <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-brand-accent" />
                        <p className="text-xs font-black text-text-muted uppercase tracking-widest">AI Analyzing...</p>
                      </div>
                    ) : aiInsight && (
                      <>
                        <div className="glass-card p-6 border-brand-accent/20 bg-brand-accent/5 relative overflow-hidden">
                          <h3 className="text-xs font-black tracking-widest text-brand-accent mb-3 uppercase flex items-center gap-2">
                            <Sparkles size={12} /> AI Explainer
                          </h3>
                          <div className="inline-block px-3 py-1 rounded-full bg-brand-accent text-white text-[10px] font-black uppercase mb-3">
                            {aiInsight.classification}
                          </div>
                          <p className="text-sm font-medium leading-relaxed italic opacity-90">"{aiInsight.brief}"</p>
                          <div className="relative mt-4 group/lock">
                            {!isPremium && (
                              <div className="absolute inset-0 z-10 backdrop-blur-md bg-[var(--color-surface-card)] rounded-xl flex flex-col items-center justify-center p-4 border border-[var(--color-border)] cursor-pointer"
                                onClick={() => setShowPaywall(true)}>
                                <Lock className="text-brand-primary mb-2" size={20} />
                                <p className="text-xs font-black text-center uppercase tracking-wider leading-relaxed opacity-80">Upgrade to unlock<br />Full Explanation</p>
                              </div>
                            )}
                            <div className={`space-y-3 ${!isPremium ? 'opacity-20 blur-sm pointer-events-none' : ''}`}>
                              <p className="text-xs text-text-muted leading-relaxed">{aiInsight.deep}</p>
                              {aiInsight.tip && (
                                <div className="bg-brand-secondary/10 border border-brand-secondary/20 p-3 rounded-xl">
                                  <p className="text-[10px] font-black text-brand-secondary uppercase mb-1">💡 Tip</p>
                                  <p className="text-xs text-text-muted">{aiInsight.tip}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                        <div className="glass-card p-5 text-[11px]">
                          <p className="font-bold text-text-muted flex items-center gap-2"><CheckCircle2 size={12} className="text-brand-secondary" /> PEER INSIGHT</p>
                          <p className="mt-2 opacity-60">90% who got this wrong also struggle with <span className="text-brand-secondary font-bold">"{aiInsight.prerequisites?.[0] || 'this concept'}"</span>.</p>
                        </div>
                      </>
                    )}
                  </motion.div>
                )}

                {isSubmitted && selectedOption === questions[currentIndex]?.answer && (
                  <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                    className="glass-card p-6 border-green-500/20 bg-green-500/5 text-center space-y-3">
                    <CheckCircle2 className="text-green-500 mx-auto" size={32} />
                    <h3 className="font-black text-green-400">Correct!</h3>
                    <p className="text-xs text-text-muted leading-relaxed">{questions[currentIndex].explanation}</p>
                  </motion.div>
                )}

                {!isSubmitted && (
                  <div className="glass-card p-8 border-dashed flex flex-col items-center justify-center text-center space-y-4 opacity-40">
                    <div className="w-12 h-12 rounded-full border-2 border-dashed border-[var(--color-border)] flex items-center justify-center animate-spin" style={{ animationDuration: '10s' }}>
                      <Sparkles size={20} className="text-text-muted" />
                    </div>
                    <p className="text-xs font-bold text-text-muted uppercase tracking-[0.2em]">Awaiting Analysis...</p>
                  </div>
                )}
              </AnimatePresence>
            </div>
          </motion.div>
        ) : (
          <motion.div key="notes" initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -10 }}>
            <AINotesPanel exam={currentExam} subject={subject} mistakes={sessionMistakes} />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
